name: 'Run Polar Tests'
description: 'Runs tests in all .polar files in the current repo'
author: 'Oso'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'user-check'
  color: 'purple'

# Define your inputs here.
inputs:
  oso-cloud-api-key:
    description: API key to the Oso Cloud environment against which you wish to run the polar tests.

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
